{
 "title": "Postgresql Benchmark Load",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(query,job)" } },
   { "name": "table", "query": { "query": "label_values(query,table)" } },
   { "name": "interval" },
   {
    "name": "run_ts",
    "query": {
     "query": "label_values(finished_at,run_ts)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iterations{run_ts=~\"$run_ts\",job=~\"$job\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(table) (table_size{table=~\"$table\", run_ts=~\"$run_ts\",job=~\"$job\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sum Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(table) (query_sum{table=~\"$table\", run_ts=~\"$run_ts\",job=~\"$job\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "No of inserts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(query_count{table=~\"$table\", run_ts=~\"$run_ts\",job=~\"$job\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Duration per statement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "p50",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(table) (query{quantile=~\"0.5\", table=~\"$table\", run_ts=~\"$run_ts\",job=~\"$job\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "p90",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(table) (query{quantile=~\"0.9\", table=~\"$table\", run_ts=~\"$run_ts\",job=~\"$job\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "p99",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(table) (query{quantile=~\"0.99\", table=~\"$table\", run_ts=~\"$run_ts\",job=~\"$job\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}